INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:Username or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
WARNING:django.request:Not Found: /admin
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-07 13:12:36.164981 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-07 13:14:33.461382 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-07 13:15:08.370361 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:15:46.824023 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:16:31.899963 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:16:56.637936 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
ERROR:root:User not registered in email login request
WARNING:django.request:Not Found: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:root:[2024-08-07 13:17:20.923452 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:17.328611 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:19.444043 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:21.294968 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:22.843520 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:23.980116 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:25.328060 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:26.411596 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:27.764077 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:37.962933 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:39.691933 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:41.027503 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:42.459843 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:43.494531 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:44.644462 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:45.743770 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:46.911015 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:22:48.062500 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
INFO:root:[2024-08-07 13:23:59.148585 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:00.864439 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:05.925499 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:07.846435 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:09.212216 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:10.588061 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:11.990806 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:13.224744 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:14.568758 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:15.915111 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:18.726287 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:20.179123 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:21.360231 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:22.908562 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:23.766353 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:25.178329 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:39.442594 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:41.594140 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:50.960724 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:24:59.325731 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:00.425165 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:01.491492 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:02.808718 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:03.828289 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:31.358591 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:32.408735 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:33.407791 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:34.374231 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:35.924860 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:36.940462 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:42.641149 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:44.377109 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:45.424339 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:46.374946 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:47.509853 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:25:48.057489 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:02.206754 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:03.325211 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:04.406178 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:05.324452 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:06.342216 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:07.274445 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:08.519027 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:09.757268 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:17.107758 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:18.443587 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:24.240841 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:25.641935 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:26.740624 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:28.676817 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:34.805614 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:36.872570 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:47.807426 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:48.923512 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:58.606778 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:26:59.655133 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:27:07.251019 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:27:08.377258 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:27:15.175665 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:27:21.287894 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:40:36.219362 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:43:34.149047 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:48:52.293087 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:50:23.926773 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:51:06.691763 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 13:51:26.583650 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 14:04:14.217528 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-07 14:04:28.985360 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
INFO:root:[2024-08-07 14:08:57.912162 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
ERROR:root:email or password not provided in email login request
WARNING:django.request:Bad Request: /api/login/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/register/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-07 16:41:57.792248 :: 127.0.0.1] Registration Successful for user: ahmedsaminp@gmail.com with Email
INFO:root:[2024-08-07 16:45:27.333124 :: 127.0.0.1] Registration Successful for user: akapushpitachowdhury@gmail.con with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/add/expense-income/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 120, in AddExpenseIncome
    title=data['title'],
          ~~~~^^^^^^^^^
KeyError: 'title'
ERROR:django.request:Internal Server Error: /api/add/expense-income/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 120, in AddExpenseIncome
    title=data['title'],
          ~~~~^^^^^^^^^
KeyError: 'title'
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/add/expense-income/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 121, in AddExpenseIncome
    title=data['title'],
          ~~~~^^^^^^^^^
KeyError: 'title'
ERROR:django.request:Internal Server Error: /api/add/expense-income/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 126, in AddExpenseIncome
    type=data['type'],
         ~~~~^^^^^^^^
KeyError: 'type'
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\admin.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'q'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'q'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'q'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'q'.
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 141, in GetExpenseIncome7Days
    data = ExpenseIncome.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pushpita-4675b-b0969-674a7-d91cc-588d5-ac55d'.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 135, in GetExpenseIncome7Days
    page = int(request.GET.get('page', 1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-08 14:40:40.584749 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
ERROR:root:User not registered in email login request
WARNING:django.request:Not Found: /api/login/
ERROR:root:User not registered in email login request
WARNING:django.request:Not Found: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
ERROR:root:Wrong email or password in email login request
WARNING:django.request:Unauthorized: /api/login/
INFO:root:[2024-08-08 14:58:11.145533 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 147, in GetExpenseIncome7Days
    paginator = Paginator(data, row_per_page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\paginator.py", line 47, in __init__
    self.per_page = int(per_page)
                    ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
WARNING:django.request:Bad Request: /api/get/expense-income/7days/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\models.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/get/expense-income/7days/
Traceback (most recent call last):
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\api\views.py", line 155, in GetExpenseIncome7Days
    serialized_data = ExpenseIncomeSerializer(data, many=True).data
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\Git\Expense_Management_System\venv\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `__all__` is not valid for model `ExpenseIncome` in `api.serializers.ExpenseIncomeSerializer`.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\serializers.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
WARNING:django.request:Method Not Allowed (GET): /api/delete/expense-income/7days/
WARNING:django.request:Method Not Allowed (DELETE): /api/delete/expense-income/7days/
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-09 15:15:02.275886 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\urls.py changed, reloading.
INFO:root:[2024-08-10 02:36:49.522168 :: 192.168.68.106] Login Successful for user: prassamin@gmail.com with Email
INFO:root:[2024-08-10 03:07:39.767978 :: 192.168.68.106] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\api\views.py changed, reloading.
INFO:root:[2024-08-11 06:09:59.447631 :: 127.0.0.1] Login Successful for user: prassamin@gmail.com with Email
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\settings.py changed, reloading.
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\wsgi.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\settings.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\settings.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\settings.py changed, reloading.
INFO:django.utils.autoreload:R:\Git\Expense_Management_System\Expense_Management_System\settings.py changed, reloading.
